/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_milanoo_meco_JniBlur_StringFromJni */

#ifndef _Included_com_milanoo_meco_JniBlur_StringFromJni
#define _Included_com_milanoo_meco_JniBlur_StringFromJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_milanoo_meco_JniBlur_StringFromJni
 * Method:    getStringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_milanoo_meco_JniBlur_StringFromJni_getStringFromJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
